### ISSUE TITLE
Update NuGet packages

### ISSUE THREAD

**Issue by tfreitasleal** [MvvmFx/MvvmFx#12]

**Comment by ahanoff** [comment]
@tfreitasleal when is 3.0.0 will be available? Thanks

**Comment by tfreitasleal** [comment]
It would be nice to have it ready by the end of November. This is just a wish, not a promise.
Are you willing to help get it done?

**Comment by ahanoff** [comment]
@tfreitasleal  actually no 😄  it depends how many issues need to be completed

**Comment by tfreitasleal** [comment]
Just #15 View isn't disposed, ever. I have it solved and tested on a real world application so it's just a question of committing the change.
What's left to do is to update Nuget packages files. And test install before publishing...
Can you handle the Nuget definition files?

**Comment by ahanoff** [comment]
@tfreitasleal If you mean .nuspec files, yes, I can.

**Comment by tfreitasleal** [comment]
I do mean .nuspec files. Please go ahead.
I'll commit the fix for #15. This week end.

**Comment by tfreitasleal** [comment]
All fixes committed. You can handle the .nuspec files.

**Comment by vector-man** [comment]
Any news on when we can get new packages on nuget?

**Comment by tfreitasleal** [comment]
Hi @ahanoff 
Are you available to go ahead with the NuSpec files?

**Comment by tfreitasleal** [comment]
Now I need this done. Finishing the port to Wisej and will take care of NuGet packages.
I must say release 3.0 will discontinued some bits and pieces:

1. support for .NET4
2. support for Visual WebGUI
3. Support for MvvmLight
