### ISSUE TITLE
CSLA and WinForms

### ISSUE THREAD

**Issue by sanyo-ok** [MvvmFx/MvvmFx#14]
Hello,

I was just looking for a "best pattern" method of binding WinForms controls like DevExpress XtraGrid to nHibernate collections. I did my own code using BindingSource, it works even with multilevel (master/detail) grids - any amount of levels.

I was aware there is better method to build applications using business level frameworks like CSLA.
It also has data binding features even for WinForms:
http://nugetmusthaves.com/Package/CSLA-WindowsForms

Then I read it is a good idea to use a ModelView pattern, especially if used together with XAML based GUI like WPF, UWP, etc. according to "Rockford Lhotka":
http://www.lhotka.net/weblog/WhyMVVM.aspx

There is an adapter for CaliburnMicro and specifically mod for WinForms:
https://github.com/MvvmFx/MvvmFx

Please suggest, is it a good idea to use following chain of components:
DevExpress WinForms XtragGrid -> MVVM->CSLA->nHibernate
?
I am reluctant to switch to WPF until MS unveils their plans to make WPF crossplatform at least on Linux.

For now DevExpress WinForms works fine on Linux + Wine and I do not have to spend time on learning WPF, look and feel of DevExpress WinForm is ok for me though my DXP license includes WPF too.

**Comment by tfreitasleal** [comment]
Hi,

I never tested MvvmFx with DevExpress. All I can do is suggest you give it a try.

**Comment by sanyo-ok** [comment]
I will try, but I need to collect preliminary information to evaluate appropriateness.

More questions please:
1) Do any examples exist which demonstrate binding general Microsoft WinForms Grid control to MVVM + CSLA ?
2) Does a good example of using CSLA with nHibernate exist?
I remember a few years ago ProjectTracker was mentioned as an example of NH.

Also a very good tool:
http://forums.asp.net/t/1782254.aspx?Code+Complete+5+0+Released
recently existed to generate code for CSLA and nHibernate integration.

I still have a demo on my HDD, but their website looks dead, therefore no way to purchase and get a support. I wonder what happened to it?
I have seen many generators which could do code for only one of CSLA or NH, but not for both of them integrated. Do you know any competitor who produces something comparable, which can demonstrate how to use NH from CSLA DataPortal in a professional manner?

Preferably an example of multiple detail  levels of the grid.

**Comment by tfreitasleal** [comment]
Hi,

Please post generic CSLA question (NHibernate, etc) on the new [CSLA forum](https://github.com/MarimerLLC/cslaforum/issues).

On the MvvmFx project, there is a [CSLA .NET sample](https://github.com/MvvmFx/MvvmFx/tree/master/Samples/CaliburnMicro/CslaSample).It's a documents&folders application, that is DB connected. You have
List of folders -> select one folder => List of documents -> select one document => Document detail.

There are Windows Forms samples (.NET 4.5 and 4.5.1) and there are also Visual WebGUI samples. VWG is a replica of the Windows Forms namespace and controls, implemented for WEB. This means you take a Windows Forms application, make some changes to the UI files and you have a running WEB application, and on top of that, it rns much faster than regular WEB applications (no magic involved: it does things differently and gets very different throughput results). Of course DevExpress controls won't run in VWG. Download the [VWG installer](https://files.vwgsupport.com/Handlers/AnonymousDownload.ashx?folder=1596214a&path=Version+10%5cv10.0.5%5cProfessional+-+no+sources) and give it a try.

Code generation - I run the [CslaGenFork](https://cslagenfork.codeplex.com/) project. It's an open source, free, code generator for CSLA only (it doesn't generate code for NHibernate). It supports DAL, DAL interface, etc. Questions on the project's forum, please.

**Comment by sanyo-ok** [comment]
Can you please also suggest why MVVM is needed for WinForms at all?
With XAML GUI I guess it is needed to port say from WPF to Silverlight and vice versa

Why do we need code separation for WinForms? 
Does it actually happens when using WinForms with Caliburn?
Is it easier to reuse the code when moving to XAML GUI?
Is it easier to assign form design to non programmers due to loose coupling of code with design?

**Comment by sanyo-ok** [comment]
I guess my last question is answered here:
https://stackoverflow.com/questions/982978/mvvm-for-winforms

**Comment by tfreitasleal** [comment]
Actually ALL your questions are answered there.
